services:
  db:
    image: postgres:15-alpine
    container_name: shop_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shopandchil
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: shop_backend
    restart: always
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/shopandchil
      - JWT_SECRET=shop_and_chil_super_secret_key_123!
      - UPLOAD_FOLDER=/app/app/uploads
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: shop_frontend
    restart: always
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  pgdata:
